### ISSUE TITLE
支持外部播放音乐显示内嵌信息

### ISSUE THREAD

**Issue by madara9212** [Moriafly/SaltPlayerSource#46]
从文件管理播放音乐，有时候只能打开软件，不能播放。

**Comment by keristen** [comment]
的确是，基本上都是这样

**Comment by Moriafly** [comment]
5.0.0-beta01 已修复

**Comment by keristen** [comment]
sorry，刚才试了试，从文件管理器打开音乐时选择椒盐音乐，仍无法识别内嵌歌词和封面，问题依然存在。







---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月19日(周五) 晚上8:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Moriafly/SaltPlayerSource] 从外部播放音乐bug (#46)




 
5.0.0-beta01 已修复
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
